services:
  kong:
    image: kong:3.5-ubuntu
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 120s
      timeout: 10s
      retries: 3
    ports:
      - 8001:8001
      - 8444:8444
      - 80:8000
      - 443:8443
    volumes:
      - ./kong:/kong
    networks:
      - kong-net
  service1:
    image: simonkowallik/httpbin
    ports:
      - 80
    environment:
      XHTTPBIN_X_service: service1
    networks:
      - kong-net
  service2:
    image: simonkowallik/httpbin
    ports:
      - 80
    environment:
      XHTTPBIN_X_service: service2
    networks:
      - kong-net
  service3:
    image: simonkowallik/httpbin
    ports:
      - 80
    environment:
      XHTTPBIN_X_service: service3
    networks:
      - kong-net

networks:
  kong-net:
   driver: bridge